name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.GH_SSH_KEY }}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Install dependencies
      run: uv sync
    - name: Run Script
      run: uv run main.py
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker Image
      uses: docker/build-push-action@v6
      with:
        context: webservice
        file: webservice/Dockerfile
        push: false
        load: true
        tags: headout-test:latest
    - name: Export Image to disk
      run: docker save --output="headout-test.tar" headout-test:latest
    - name: Tree
      run: tree 
    - name: Copy Image via SSH
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        source: headout-test.tar
        target: ~/app
    - name: Start container in EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd ~/app
          WS_NAME=headout-webserver
          docker ps -q --filter "name=$WS_NAME" |xargs --no-run-if-empty docker stop
          docker ps -aq --filter "name=$WS_NAME" |xargs --no-run-if-empty docker rm
          docker load -i headout-test.tar
          docker run --detach -p80:9000 --name $WS_NAME headout-test
